### ISSUE TITLE
Data encryption/decryption

### ISSUE THREAD

**Issue by dominic-healid** [EOSIO/eosio-swift-ecc#82]
Do you have sample code or documentation how to do this here?

**Comment by dominic-healid** [comment]
Is this code from eosjs-ecc can also be done using this library?

```
let {ecc} = Eos.modules

message = 'the data'

someonesPrivateKey=ecc.PrivateKey.fromSeed('someone')
someonesPublicKey=someonesPrivateKey.toPublic()

myPrivate=ecc.PrivateKey.fromSeed('my')
myPublic=myPrivate.toPublic()

encryptedMessage = ecc.Aes.encrypt(myPrivate, someonesPublicKey, message)
assert.equal(message, ecc.Aes.decrypt(someonesPrivateKey, myPublic,
  encryptedMessage.nonce, encryptedMessage.message, encryptedMessage.checksum))
```

**Comment by opi-smccoole** [comment]
Sorry the library currently does not support message encryption, nor does it support signing messages for a specific public key recipient.  The ECC functions are currently largely targeted at what is necessary for signing and sending transactions to the blockchain rather than providing a general purpose cryptography library.
